### ISSUE TITLE
PaHM Integration in ufs-coastal

### ISSUE THREAD

**Issue by pvelissariou1** [oceanmodeling/ufs-weather-model#10]
@uturuncoglu  @saeed-moghimi-noaa  I am creating new issue for PaHM integration. So, we could keep communicating about integration issues that we might have.

**Comment by janahaddad** [comment]
I suggest closing this since the discussion is happening in noaa-ocs-modeling/SurgeTeamCoordination#68

**Comment by pvelissariou1** [comment]
I am closing this issue as completed
