### ISSUE TITLE
SCHISM standalone (outside UFS-Coastal) for Ian on HSOFS mesh

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#105]

**Comment by janahaddad** [comment]
@yunfangsun add location here so we can close

**Comment by yunfangsun** [comment]
/work2/noaa/nos-surge/yunfangs/hurricane_ian/sch_alone_hsofs on Hercules

**Comment by janahaddad** [comment]
Thanks @yunfangsun !

**Comment by janahaddad** [comment]
Update 6/3: 
* SCHISM run completed
* need to eventually compare with obs, but for now continue to build the mechanistic/numerical coupling
