### ISSUE TITLE
Re-produce ufs coastal DATM+SCHISM test case for H. Ian with HSOFS mesh

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#109]
@Armaghan-NOAA what we discussed is reproducing @yunfangsun 's datm+schism case. Please note here anything you believe is noteworthy during that process, as relates to a potential workflow for facilitiating the building and configuring a user-defined application.

**Comment by Armaghan-NOAA** [comment]
I'll be adapting testcase from Yunfang's directory here: 

/work2/noaa/nos-surge/yunfangs/hurricane_ian/ufs_atm2sch_hsofs

@yunfangsun could you confirm this is the directory related to DATM+SCHISM?

**Comment by yunfangsun** [comment]
@Armaghan-NOAA 

Yes, it is the directory.

**Comment by Armaghan-NOAA** [comment]
The directory I am working on is: /work2/noaa/nos-surge/armaghan/hurricane_ian/ufs_atm2sch_hsofs

**Comment by Armaghan-NOAA** [comment]
Notes from Gchat:

from Armaghan:
Hi Yunfang! I copied your directory to mine: /work2/noaa/nos-surge/armaghan/hurricane_ian/ufs_atm2sch_hsofsI want to change the run time in job_card but it gives me this error:"job_card""job_card" E212: Can't open file for writingPress ENTER or type command to continueI tried chmod -R 755 .Does'nt help! Do you have any idea what may be wrong?

from Yungfang:
I see the file in your folder (4.0K -rw-r--r-- 1 yunfangs nos-surge 1.2K Jun  6 14:45 job_card)It should be your file nowbut it seems that the file owner is still me

from Armaghan:
Do you have any idea what I can do to make the folder in my name?

from Yungfang:
I am trying to change ownership, but it seems that I don't have the permissionhown: changing ownership of 'RESTART': Operation not permittedchown: changing ownership of 'rpointer.atm': Operation not permittedchown: changing ownership of 'rpointer.cpl': Operation not permittedchown: changing ownership of 'testout': Operation not permittedchown: changing ownership of 'ufs.configure': Operation not permittedchown: changing ownership of 'ufs.configure_sch': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-03600.nc](http://ufs.cpld.cpl.hi.2022-09-15-03600.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-07200.nc](http://ufs.cpld.cpl.hi.2022-09-15-07200.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-10800.nc](http://ufs.cpld.cpl.hi.2022-09-15-10800.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-14400.nc](http://ufs.cpld.cpl.hi.2022-09-15-14400.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-18000.nc](http://ufs.cpld.cpl.hi.2022-09-15-18000.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-21600.nc](http://ufs.cpld.cpl.hi.2022-09-15-21600.nc/)': Operation not permittedchown: changing ownership of '[vgrid.in](http://vgrid.in/)': Operation not permittedchown: changing ownership of 'windrot_geo2proj.gr3': Operation not permitted

I think you can write to the hercules help desk.

**Comment by Armaghan-NOAA** [comment]
> Notes from Gchat:
> 
> from Armaghan: Hi Yunfang! I copied your directory to mine: /work2/noaa/nos-surge/armaghan/hurricane_ian/ufs_atm2sch_hsofsI want to change the run time in job_card but it gives me this error:"job_card""job_card" E212: Can't open file for writingPress ENTER or type command to continueI tried chmod -R 755 .Does'nt help! Do you have any idea what may be wrong?
> 
> from Yungfang: I see the file in your folder (4.0K -rw-r--r-- 1 yunfangs nos-surge 1.2K Jun  6 14:45 job_card)It should be your file nowbut it seems that the file owner is still me
> 
> from Armaghan: Do you have any idea what I can do to make the folder in my name?
> 
> from Yungfang: I am trying to change ownership, but it seems that I don't have the permissionhown: changing ownership of 'RESTART': Operation not permittedchown: changing ownership of 'rpointer.atm': Operation not permittedchown: changing ownership of 'rpointer.cpl': Operation not permittedchown: changing ownership of 'testout': Operation not permittedchown: changing ownership of 'ufs.configure': Operation not permittedchown: changing ownership of 'ufs.configure_sch': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-03600.nc](http://ufs.cpld.cpl.hi.2022-09-15-03600.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-07200.nc](http://ufs.cpld.cpl.hi.2022-09-15-07200.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-10800.nc](http://ufs.cpld.cpl.hi.2022-09-15-10800.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-14400.nc](http://ufs.cpld.cpl.hi.2022-09-15-14400.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-18000.nc](http://ufs.cpld.cpl.hi.2022-09-15-18000.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-21600.nc](http://ufs.cpld.cpl.hi.2022-09-15-21600.nc/)': Operation not permittedchown: changing ownership of '[vgrid.in](http://vgrid.in/)': Operation not permittedchown: changing ownership of 'windrot_geo2proj.gr3': Operation not permitted
> 
> I think you can write to the hercules help desk.

I already wrote for Hercules Helpdesk. They contacted Ed for permission and I cc'ed Jana and Saeed on that email.

**Comment by Armaghan-NOAA** [comment]
> > Notes from Gchat:
> > from Armaghan: Hi Yunfang! I copied your directory to mine: /work2/noaa/nos-surge/armaghan/hurricane_ian/ufs_atm2sch_hsofsI want to change the run time in job_card but it gives me this error:"job_card""job_card" E212: Can't open file for writingPress ENTER or type command to continueI tried chmod -R 755 .Does'nt help! Do you have any idea what may be wrong?
> > from Yungfang: I see the file in your folder (4.0K -rw-r--r-- 1 yunfangs nos-surge 1.2K Jun  6 14:45 job_card)It should be your file nowbut it seems that the file owner is still me
> > from Armaghan: Do you have any idea what I can do to make the folder in my name?
> > from Yungfang: I am trying to change ownership, but it seems that I don't have the permissionhown: changing ownership of 'RESTART': Operation not permittedchown: changing ownership of 'rpointer.atm': Operation not permittedchown: changing ownership of 'rpointer.cpl': Operation not permittedchown: changing ownership of 'testout': Operation not permittedchown: changing ownership of 'ufs.configure': Operation not permittedchown: changing ownership of 'ufs.configure_sch': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-03600.nc](http://ufs.cpld.cpl.hi.2022-09-15-03600.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-07200.nc](http://ufs.cpld.cpl.hi.2022-09-15-07200.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-10800.nc](http://ufs.cpld.cpl.hi.2022-09-15-10800.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-14400.nc](http://ufs.cpld.cpl.hi.2022-09-15-14400.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-18000.nc](http://ufs.cpld.cpl.hi.2022-09-15-18000.nc/)': Operation not permittedchown: changing ownership of '[ufs.cpld.cpl.hi.2022-09-15-21600.nc](http://ufs.cpld.cpl.hi.2022-09-15-21600.nc/)': Operation not permittedchown: changing ownership of '[vgrid.in](http://vgrid.in/)': Operation not permittedchown: changing ownership of 'windrot_geo2proj.gr3': Operation not permitted
> > I think you can write to the hercules help desk.
> 
> I already wrote for Hercules Helpdesk. They contacted Ed for permission and I cc'ed Jana and Saeed on that email.

I followed up with my request with Ed. He kindly provided the permission to own the folders I copied from Yunfang's directory on Hercules.

**Comment by mansurjisan** [comment]
## Hurricane Ian DATM+SCHISM Simulation Update
I successfully ran the Hurricane Ian DATM+SCHISM simulation using input files from @yunfangsun 's directory. The simulation completed without errors.

- **Run Directory**: `/work/noaa/nosofs/mjisan/ufs-weather-model/tests/stmp/mjisan/FV3_RT/coastal_ian_atm2sch_v2`
- **Executable Used**: Pre-built executable from @yunfangsun's directory
- **Status**: Completed successfully
- **Pending**: Result visualization and analysis


### Issue with Self-Built Executable

I attempted to use an executable I built during the RT test for the **coastal_ike_shinnecock_atm2sch** simulation to run the Hurricane Ike case. This attempt was unsuccessful.

#### Build Details:
- **Compile Script Options**:
"-DAPP=CSTLS -DUSE_ATMOS=ON -DNO_PARAMETIS=OFF -DOLDIO=ON"


Upon comparing the two executables:
1. @yunfangsun executable appears to be built using Spack-stack 1.5.1
2. My built executable seems to be based on Spack-stack 1.6.0

@yunfangsun ,  @janahaddad , Could the difference in Spack-stack versions be causing the incompatibility?

**Comment by yunfangsun** [comment]
Hi @mansurjisan ,

The configuration is based on an older version of UFS-Coastal, I will work on converting it to compatible with the updated ufs-coastal.

**Comment by mansurjisan** [comment]
Thank you, @yunfangsun ! I appreciate it. I am also looking into this issue.

**Comment by mansurjisan** [comment]
Hi @uturuncoglu , I just changed the permissions for the Hurricane Ian simulation directories. Here are the relevant paths:

1. Attempted execution with my built executable (from atm2sch RT case):

`/work/noaa/nosofs/mjisan/ufs-weather-model/tests/stmp/mjisan/FV3_RT/coastal_ian_atm2sch`

2. Successful execution using @yunfangsun 's built executable:

`/work/noaa/nosofs/mjisan/ufs-weather-model/tests/stmp/mjisan/FV3_RT/coastal_ian_atm2sch_v2`

## Error Encountered

When attempting to run the simulation with my executable, I encountered the following error:

+ srun --label -n 480 ./fv3_atm2sch_intel.exe
117:  ESMF_Initialize: Error initializing framework

The error seems to be related to ESMF_Initialize.

The simulation runs successfully with @yunfangsun's executable, suggesting a potential issue with my build process or configuration.

@uturuncoglu  , if you have any insights or suggestions regarding this ESMF initialization error, your input would be greatly appreciated.

**Comment by yunfangsun** [comment]
Hi @mansurjisan,

Could you please try /work2/noaa/nosofs/yunfangs/hurricane_ian/atm_sch_new/coastal_ian_subset_atm2sch_intel_1 ?

Please let me know if this case works with your compiled executable file.

Thank you!

**Comment by mansurjisan** [comment]
> Hi @mansurjisan,
> 
> Could you please try /work2/noaa/nosofs/yunfangs/hurricane_ian/atm_sch_new/coastal_ian_subset_atm2sch_intel_1 ?
> 
> Please let me know if this case works with your compiled executable file.
> 
> Thank you!

Hi @yunfangsun, Thank you very much for looking into this. I appreciate your help. I copied your files and was able to run the model using my version of `fv3.exe`. It looks to me like the param.nml was significantly different in the previous version of this run. 

This is the directory where I submitted the new job:

`/work/noaa/nosofs/mjisan/ufs-weather-model/tests/stmp/mjisan/FV3_RT/coastal_ian_atm2sch_v4`

If you notice anything unusual, please let me know. 

I am currently working on visualizing a few output variables.

I tried to use the `combine_output11_MPI` executable to combine all the schout_*.nc files, but the pre-built version of the executable didn't work for me due to issues with NetCDF versions. I recompiled the code, and now it's working fine. 

When you post-process the outputs, do you usually combine the NetCDF files or read each file individually in Python?

Thanks again for your help!

-Mansur

**Comment by yunfangsun** [comment]
Hi @mansurjisan 

Thank you for trying the new configuration! I am glad that it works now.

I am using the combined NetCDF files for post-processing, and I didn't directly read each file individually in Python.
