### ISSUE TITLE
Ufs-Coastal SCHISM test

### ISSUE THREAD

**Issue by yunfangsun** [oceanmodeling/ufs-weather-model#11]
Hi Ufuk and Takis, @uturuncoglu @pvelissariou1 

I am including here the threads that we talked about today.

There is a compiling error may be caused by SCHISM:

<+ OMP_NUM_THREADS=1
+ make -j 8 VERBOSE=1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(43): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ELEVCLASS]
  subroutine glc_get_elevation_classes_with_bareland(glc_ice_covered, glc_topo, glc_elevclass, logunit)
--------------------------------------------------------------------------------^
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(36): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ELEVCLASS]
  subroutine glc_get_elevation_classes_without_bareland(glc_topo, glc_elevclass, logunit)
------------------------------------------------------------------^
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(59): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ICEFRAC_EC]
  subroutine glc_get_fractional_icecov(nec, glc_topo, glc_icefrac, glc_icefrac_ec, logunit)
-------------------------------------------------------------------^
+ mv /work/noaa/nosofs/yunfangs/ufs-ww3/stmp/yunfangs/FV3_RT/rt_352372/compile_3_intel/build_fv3_3_intel/ufs_model /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/fv3_3_intel.exe
+ [[ orion == linux ]]
+ cp /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/modulefiles/ufs_orion.intel.lua /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/modules.fv3_3_intel.lua
+ '[' YES = YES ']'
+ rm -rf /work/noaa/nosofs/yunfangs/ufs-ww3/stmp/yunfangs/FV3_RT/rt_352372/compile_3_intel/build_fv3_3_intel
+ elapsed=91
+ echo 'Elapsed time 91 seconds. Compiling -DAPP=CSTLS -DNO_PARMETIS=OFF -DOLDIO=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release finished'
+ echo 'Compile 3_intel elapsed time 91 seconds. -DAPP=CSTLS -DNO_PARMETIS=OFF -DOLDIO=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release'
++ date
+ echo 'Compile ended:    ' Sun Aug 27 22:17:27 CDT 2023
++ date +%s
+ echo -n ' 1693192647,'>

the error message for the regression test is as follows:

5: forrtl: error (78): process killed (SIGTERM)
5: Image              PC                Routine            Line        Source
5: fv3.exe            000000000244B97B  Unknown               Unknown  Unknown
5: libc-2.17.so       00002AAFF5128340  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF372A5BC  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF36368AE  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF3652568  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF361CC90  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF35FC7EC  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF373F66D  Unknown               Unknown  Unknown
5: libmpi.so.12.0.0   00002AAFF35DF82F  MPI_Bcast             Unknown  Unknown
5: libmpifort.so.12.  00002AAFF31B53E4  pmpi_bcast            Unknown  Unknown
5: fv3.exe            0000000001DE866D  schism_init_             3232  schism_init.F90
5: fv3.exe            0000000001D5748D  schism_nuopc_cap_         339  schism_nuopc_cap.F90
5: fv3.exe            00000000009AB464  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
5: fv3.exe            00000000009AF3E6  ESMCI_FTableCallE         824  ESMCI_FTable.C
5: fv3.exe            00000000008454BB  _ZN5ESMCI3VMK5ent        1112  ESMCI_VMKernel.C
5: fv3.exe            000000000077C1AA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
5: fv3.exe            00000000009ACAF7  c_esmc_ftablecall         981  ESMCI_FTable.C
5: fv3.exe            000000000080A29D  esmf_compmod_mp_e        1222  ESMF_Comp.F90
5: fv3.exe            0000000000C07246  esmf_gridcompmod_        1407  ESMF_GridComp.F90
5: fv3.exe            00000000007B1048  nuopc_driver_mp_l        2565  NUOPC_Driver.F90
5: fv3.exe            00000000007D5C17  nuopc_driver_mp_i        1260  NUOPC_Driver.F90
5: fv3.exe            00000000007DEAFE  nuopc_driver_mp_i         455  NUOPC_Driver.F90
5: fv3.exe            00000000009AB464  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
5: fv3.exe            00000000009AF3E6  ESMCI_FTableCallE         824  ESMCI_FTable.C
5: fv3.exe            00000000008452CF  _ZN5ESMCI3VMK5ent        2308  ESMCI_VMKernel.C
5: fv3.exe            000000000077C1AA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
5: fv3.exe            00000000009ACAF7  c_esmc_ftablecall         981  ESMCI_FTable.C
5: fv3.exe            000000000080A29D  esmf_compmod_mp_e        1222  ESMF_Comp.F90
5: fv3.exe            0000000000C07246  esmf_gridcompmod_        1407  ESMF_GridComp.F90
5: fv3.exe            000000000041996E  MAIN__                    381  UFS.F90
5: fv3.exe            00000000004189E2  Unknown               Unknown  Unknown
5: libc-2.17.so       00002AAFF5114495  __libc_start_main     Unknown  Unknown
5: fv3.exe            00000000004188E9  Unknown               Unknown  Unknown
srun: error: Orion-24-02: tasks 0-2,4-5: Exited with exit code 1

The out log is as follows:

Model started:   Mon Aug 28 00:23:38 CDT 2023
0:
0:
0: * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
0:      PROGRAM ufs       HAS BEGUN. COMPILED       0.00     ORG: np23
0:      STARTING DATE-TIME  AUG 28,2023  00:23:42.913  240  MON   2460185
0:
0:

Thank you for your help!

Yunfang

**Comment by uturuncoglu** [comment]
@pvelissariou1 @yunfangsun I think I remember the issue with SCHSIM. When I updated there was a change in terms of  `nws` parameter and I wait it to be resolve before update the SCHSIM and cap. We need to check with SCHSIM developers again. So, I still did not update the component. I updated the file that is responsible to move missing file to RT run directory and push to ufs-coastal repository. @yunfangsun could you try again from scratch and let me know.

**Comment by pvelissariou1** [comment]
@ufuk, @Yunfang Sun - NOAA Affiliate ***@***.***> FYI, I updated
SCHISM in CoastalApp and the schism test cases in the testsuite.
If I remember correctly the test cases run as expected.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by uturuncoglu** [comment]
@pvelissariou1 I pushed the change to the script that creates the run directory. It most me fine now.

**Comment by yunfangsun** [comment]
Hi @uturuncoglu 
I have tried to clone the new ufs-coastal, and the compilation error kept the same, and the log stuck at the following stage:

Job id 14805681
TEST 3_intel compile_intel is waiting to enter the queue
TEST 3_intel compile_intel is submitted
1 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
2 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
3 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
4 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
5 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
6 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
7 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
8 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
9 min. TEST 3_intel compile_intel is pending,  status: PD jobid 14805681
10 min. TEST 3_intel compile_intel is running,  status: R jobid 14805681
Slurm unknown status -. Check sacct ...
14805681                COMPLETED      compile_3_intel
14805681.ba+            COMPLETED                batch
14805681.ex+            COMPLETED               extern
11 min. TEST 3_intel compile_intel is COMPLETED,  status: - jobid 14805681
+ ls -l /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/fv3_3_intel.exe
-rwxr-x--- 1 yunfangs nosofs 226266360 Aug 28 13:10 /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/fv3_3_intel.exe
+ cp /work/noaa/nosofs/yunfangs/ufs-ww3//stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/compile_3_intel_time.log /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/logs/log_orion
+ cat /work/noaa/nosofs/yunfangs/ufs-ww3//stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/job_timestamp.txt
+ remove_fail_test
+ echo 'Removing test failure flag file for compile_3_intel'
Removing test failure flag file for compile_3_intel
+ rm -f /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/fail_compile_3_intel
++ date +%s
+ echo ' 1693246304, 1'
+ elapsed=668
+ echo 'Elapsed time 668 seconds. Compile 3_intel'
Elapsed time 668 seconds. Compile 3_intel
+ '[' 0 -eq 0 ']'

**Comment by uturuncoglu** [comment]
@yunfangsun What is the actual error? Could you paste output of ` /work/noaa/nosofs/yunfangs/ufs-ww3//stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/err`. I could see `Slurm unknown status -. Check sacct ...` but this could be related with the job scheduler or the account that you are trying to run the case.

**Comment by yunfangsun** [comment]
Hi @uturuncoglu 

The error < /work/noaa/nosofs/yunfangs/ufs-ww3//stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/err > is as bellows:

 The externaly compiled ParMETIS library could not be found.  Reverting back
  to SCHISM's internal ParMETIS.


CMake Warning:
  Manually-specified variables were not used by the project:
    MPI
+ OMP_NUM_THREADS=1
+ make -j 8 VERBOSE=1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(43): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ELEVCLASS]
  subroutine glc_get_elevation_classes_with_bareland(glc_ice_covered, glc_topo, glc_elevclass, logunit)
--------------------------------------------------------------------------------^
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(36): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ELEVCLASS]
  subroutine glc_get_elevation_classes_without_bareland(glc_topo, glc_elevclass, logunit)
------------------------------------------------------------------^
/work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/CMEPS-interface/CMEPS/ufs/glc_elevclass_mod.F90(59): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [GLC_ICEFRAC_EC]
  subroutine glc_get_fractional_icecov(nec, glc_topo, glc_icefrac, glc_icefrac_ec, logunit)
-------------------------------------------------------------------^
+ mv /work/noaa/nosofs/yunfangs/ufs-ww3/stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/build_fv3_3_intel/ufs_model /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/fv3_3_intel.exe
+ [[ orion == linux ]]
+ cp /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/modulefiles/ufs_orion.intel.lua /work/noaa/nosofs/yunfangs/ufs-ww3/ufs-coastal/tests/modules.fv3_3_intel.lua
+ '[' YES = YES ']'
+ rm -rf /work/noaa/nosofs/yunfangs/ufs-ww3/stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/build_fv3_3_intel
+ elapsed=103
+ echo 'Elapsed time 103 seconds. Compiling -DAPP=CSTLS -DNO_PARMETIS=OFF -DOLDIO=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release finished'
+ echo 'Compile 3_intel elapsed time 103 seconds. -DAPP=CSTLS -DNO_PARMETIS=OFF -DOLDIO=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release'
++ date
+ echo 'Compile ended:    ' Mon Aug 28 13:10:36 CDT 2023
++ date +%s
+ echo -n ' 1693246236,'
"/work/noaa/nosofs/yunfangs/ufs-ww3//stmp/yunfangs/FV3_RT/rt_430214/compile_3_intel/err" 230L, 10388C

**Comment by pvelissariou1** [comment]
@yunfangsun <https://github.com/yunfangsun> @uturuncoglu
<https://github.com/uturuncoglu> Yunfang those issues (queue delays, etc)
are related to the slurm workflow manager I believe:
You allocations on Orion are as follows:
             Account                                                QOS
-------------------- --------------------------------------------------
           nos-surge                                           windfall
               coast                                           windfall
              nosofs                                           windfall

On the other hand my allocations are:
             Account                                                QOS
-------------------- --------------------------------------------------
           nos-surge                                           windfall
               coast                                           windfall
             coastal              batch,debug,novel,ood,urgent,windfall
              nosofs                                           windfall
                 ohd              batch,debug,novel,ood,urgent,windfall

The windfall is of the lowest priority in the queue (VERY VERY LONG WAIT
TIMES)
This is most likely why your runs for UFS-Coastal fail (other issues as
well?)
In my case, I use my coastal account and my runs go through.
I'll let Ed and Saeed know about this.




Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Yunfang, did you get the executable FV3* ?

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by yunfangsun** [comment]
Hi Takis @pvelissariou1 

Thank you! Yes, the waiting time is quite long for windfall Qos, for all the accounts: nos-surge, coast, and nosofs.

Yunfang

**Comment by uturuncoglu** [comment]
@pvelissariou1 @yunfangsun I could not see any issue with the build. I think the build works since I could see `echo 'Compile ended: ' Mon Aug 28 13:10:36 CDT 2023` in the log. If you check the run directory and verify it is working (you could see PET*, err and out files), then that is great.

**Comment by yunfangsun** [comment]
Hi Ufuk @uturuncoglu ,

The PET0.ESMF_LogFile looks like: 
20230828 132418.137 INFO             PET0  ScalarFieldCount = 3
20230828 132418.137 INFO             PET0  ScalarFieldIdxGridNX = 1
20230828 132418.137 INFO             PET0  ScalarFieldIdxGridNY = 2
20230828 132418.137 INFO             PET0  ScalarFieldIdxNextSwCday = 3
20230828 132418.137 INFO             PET0  ScalarFieldName = cpl_scalars
20230828 132418.137 INFO             PET0  start_type = startup
20230828 132418.137 INFO             PET0  restart_dir = RESTART/
20230828 132418.137 INFO             PET0  case_name = ufs.cpld
20230828 132418.137 INFO             PET0  restart_n = 12
20230828 132418.137 INFO             PET0  restart_option = nhours
20230828 132418.137 INFO             PET0  restart_ymd = -999
20230828 132418.137 INFO             PET0  orb_eccen = 1.e36
20230828 132418.137 INFO             PET0  orb_iyear = 2000
20230828 132418.137 INFO             PET0  orb_iyear_align = 2000
20230828 132418.137 INFO             PET0  orb_mode = fixed_year
20230828 132418.137 INFO             PET0  orb_mvelp = 1.e36
20230828 132418.137 INFO             PET0  orb_obliq = 1.e36
20230828 132418.137 INFO             PET0  stop_n = 24
20230828 132418.137 INFO             PET0  stop_option = nhours
20230828 132418.137 INFO             PET0  stop_ymd = -999
20230828 132418.137 INFO             PET0 ReadAttributes ALLCOMP_attributes:: end:
20230828 132418.140 INFO             PET0 (med.F90:InitializeP0): called
20230828 132418.141 INFO             PET0 (med.F90:InitializeP0): Mediator dbug_flag is      0
20230828 132418.141 INFO             PET0 (med.F90:InitializeP0): done
"PET0.ESMF_LogFile" 166L, 12032C



The /work/noaa/nosofs/yunfangs/ufs-ww3/stmp/yunfangs/FV3_RT/rt_430214/coastal_ike_shinnecock_atm2sch_intel/err looks like:

+ ulimit -s unlimited
++ date
+ echo 'Model started:  ' Mon Aug 28 13:24:13 CDT 2023
+ export OMP_STACKSIZE=512M
+ OMP_STACKSIZE=512M
+ export KMP_AFFINITY=scatter
+ KMP_AFFINITY=scatter
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ export ESMF_RUNTIME_PROFILE=ON
+ ESMF_RUNTIME_PROFILE=ON
+ export ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
+ ESMF_RUNTIME_PROFILE_OUTPUT=SUMMARY
+ sync
+ sleep 1
+ srun --label -n 6 ./fv3.exe
5: Abort(0) on node 5 (rank 2 in comm 368): application called MPI_Abort(comm=0xC4000016, 0) - process 2
3: Abort(0) on node 3 (rank 0 in comm 368): application called MPI_Abort(comm=0xC400001D, 0) - process 0
4: Abort(0) on node 4 (rank 1 in comm 368): application called MPI_Abort(comm=0xC4000016, 0) - process 1
0: slurmstepd: error: *** STEP 14805709.0 ON Orion-23-54 CANCELLED AT 2023-08-28T13:54:19 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 14805709 ON Orion-23-54 CANCELLED AT 2023-08-28T13:54:19 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
"err" 40L, 1680C


The out looks like:
Model started:   Mon Aug 28 13:24:13 CDT 2023
0:
0:
0: * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
0:      PROGRAM ufs       HAS BEGUN. COMPILED       0.00     ORG: np23
0:      STARTING DATE-TIME  AUG 28,2023  13:24:18.069  240  MON   2460185
0:
0:
3:    0: ABORT: you must have sflux_inputs_file!
5:    2: ABORT: you must have sflux_inputs_file!
4:    1: ABORT: you must have sflux_inputs_file!



It seems that I missed the sflux_inputs_file, 
Orion-login-2[273] yunfangs$ ls INPUT_DATM/
wind_atm_fin_ch_time_vec_ESMFmesh.nc  wind_atm_fin_ch_time_vec_STR_fixed.nc

**Comment by uturuncoglu** [comment]
@yunfangsun I am not sure. Maybe this is permission issue and you could get data from my RT directory. I rerun chmod command again. Please try again, if it wont run, I'll test again. It is working in my ufs-coastal copy.

**Comment by uturuncoglu** [comment]
@yunfangsun I think `sflux_inputs_file`message is coming from SCHSIM not CDEPS. So, maybe we still have inconsistency interns of parameters that needs to be used.

**Comment by pvelissariou1** [comment]
@uturuncoglu <https://github.com/uturuncoglu> @yunfangsun
<https://github.com/yunfangsun> I didn't notice any issues like that when I
ran the test case. I am pointing to:
DISKNM=/work/noaa/nems/tufuk/RT
Only thing is I did not get output files. I'll check on that later today.
There are multiple issues on Orion for us, we are working on a solution for
orion/hercules.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by yunfangsun** [comment]
@uturuncoglu Hi Ufuk,

I tried again after you changed the RT permission, the out file is still as follows:

Model started:   Mon Aug 28 15:05:53 CDT 2023
0:
0:
0: * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
0:      PROGRAM ufs       HAS BEGUN. COMPILED       0.00     ORG: np23
0:      STARTING DATE-TIME  AUG 28,2023  15:05:56.123  240  MON   2460185
0:
0:
5:    2: ABORT: you must have sflux_inputs_file!
3:    0: ABORT: you must have sflux_inputs_file!
4:    1: ABORT: you must have sflux_inputs_file!

And the output files contain no data:

4.0K -rw-r----- 1 yunfangs nosofs 4.0K Aug 28 15:05 schout_000000_1.nc
4.0K -rw-r----- 1 yunfangs nosofs 4.0K Aug 28 15:05 schout_000001_1.nc
4.0K -rw-r----- 1 yunfangs nosofs 4.0K Aug 28 15:05 schout_000002_1.nc

**Comment by pvelissariou1** [comment]
@uturuncoglu <https://github.com/uturuncoglu> @Yunfang Sun - NOAA Affiliate
***@***.***> Yunfang, I don't understand why you are getting the
error:
 ABORT: you must have sflux_inputs_file!
This is a 2D case and it does not use atmospheric fluxes.
Am I missing something here?
I have run the *atm2sch and *sch test cases using both CoastalApp and
UFS-Coastal (see my presentation for the SCHISM framework)
without noticing such issues. is the barotropic flag on in your namelist
file? Could you please double check?

Did you run this test case from within CoastalApp/CoastalApp-testsuite?
CoastalApp uses the latest version of SCHISM, so in this case you need to
add in NEMS/src/incmake/component_SCHISM the flag USE_ATMOS
in order to use the nws = 2 option.


Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by uturuncoglu** [comment]
@yunfangsun Could you reclone the ufs-coastal. I have just update the SCHSIM.

**Comment by yunfangsun** [comment]
@uturuncoglu @pvelissariou1 
Sure, I will test CoastalApp and the new ufs-coastal again.

**Comment by pvelissariou1** [comment]
Ufuk,Yunfang make sure you update the name list and use USE_ATMOS flag when
compiling SCHISM in UFS-Coastal.

On Monday, August 28, 2023, Yunfang Sun ***@***.***> wrote:
> @uturuncoglu @pvelissariou1
> Sure, I will test CoastalApp and the new ufs-coastal again.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci4.googleusercontent.com/proxy/jl2HHg9TR6-SHBNR_DV63Sj1fx0x4mBDxVuW_ulszf2UPh9FGI8Hb25M20qqHhZfrM3TLiytf6PSVAaLAo5Ug0EL1B4TNiRNNbiVaurMTJmiyrp01LVx-ysbDY64hh8eUIqaW6nD6LKQshR_haC0M67nHVSiT-zxVP66g9tEA6JJMPCGw5qRvSrpYe_zfme1jIRJ_QRFz8uqDmU5Ju4TRJX3h05gNuwvvURBoWt_h1myxHQ5lQ=s0-d-e1-ft#https://github.com/notifications/beacon/APC7TP5HPR3XCCK5NHKDWZLXXUHE5A5CNFSM6AAAAAA4BUXI76WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTFDYXMA.gif>Message
ID: ***@***.***>

-- 
Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by yunfangsun** [comment]
Hi Takis, @pvelissariou1 
I can't compile newly cloned CoastalApp both on Orion and Parallel works, the error messages are as follows:
schism_esmf_util.F90(209): error #6796: The variable must have the TARGET attribute or be a subobject of an object with the TARGET attribute, or it must have the POINTER attribute.   [IDRY_E]
  isPtr%wrap%ptrMap(14)%iarrayPtr1 => idry_e
--------------------------------------^
compilation aborted for schism_esmf_util.F90 (code 1)
make[2]: *** [schism_esmf_util.o] Error 1
make[2]: Leaving directory `/lustre/new_coast/CoastalApp/SCHISM/schism-esmf/src/schism'
make[1]: *** [src/schism/schism_bmi.o] Error 2
make[1]: Leaving directory `/lustre/new_coast/CoastalApp/SCHISM/schism-esmf'
make: *** [/lustre/new_coast/CoastalApp/SCHISM_INSTALL/schism.mk] Error 2

**Comment by pvelissariou1** [comment]
@yunfangsun @soroosh @FariborzDaneshvar-NOAA  @saeed Thanks YunFang, the issue has already reported to the SCHISM developers. Waiting from them to incorporate a fix upstream. I have a fix locally that I am testing right now.

**Comment by josephzhang8** [comment]
Hi all-

We are trying to do all UFS-coastal reg tests:

https://github.com/oceanmodeling/ufs-coastal/blob/feature/coastal_app/tests/rt_coastal.conf

There seems to be a dir missing; e.g., ### SCHISM tests: 11-15 etc need a dir called 'DATM_ATMMESH_input_data/'. It's supposed to be on Hercules: /work/noaa/epic/hercules/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/DATM_ATMMESH_input_data/ but this dir is not there. Anyone can help? Thx!!

@danishyo

**Comment by uturuncoglu** [comment]
@josephzhang8 Since this development is not merged with the ufs-weather-model, the input files are not the part of the common directories. We are maintaining them on Orion - `/work/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20221101`. I think you could access to the same directory from Hercules too. To use this directory, just open rt.sh and find the section for your platform and set DISKNM variable like following `DISKNM=/work/noaa/nems/tufuk/RT`. Then you could run the RT. In the future we are plaining to put all those input files to cloud etc. but I think we are not it that stage yet since we are still trying to make components stable and port different configurations of them. Anyway, let me know if you have still issue.

**Comment by josephzhang8** [comment]
Got it; thank you so much, @uturuncoglu!
