### ISSUE TITLE
FRF Duck NC Observations

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#135]
Exploring FRF THREDDS data server for observations at FRF Facility in Duck, NC

Using resource provided by @saeed-moghimi-noaa  here #133

**Comment by janahaddad** [comment]
I explored & plotted available observations for H. Dorian 2019. One is "[8-m array](https://chldata.erdc.dren.mil/thredds/catalog/frf/oceanography/waves/8m-array/catalog.html)" wave data. 

The field data collection was from 15 high frequency pressure gauges used to create directional wave parameters. One of the 15 gauges was chosen as the central "nominal" location for the observations. 

**Plot of the 15 gauge locations in red, with nominal station (station 111) in green:**
![image](https://github.com/user-attachments/assets/5d268577-d50f-4d13-9cdb-e159238ed6f4)

**Water level above NAVD88, sig. wave height, peak period, mean period, peak direction, mean direction:**
![image](https://github.com/user-attachments/assets/028e1fab-f09b-4324-88ef-a34e347d23b1)

**Comment by janahaddad** [comment]
@yunfangsun, sharing the scripts I created to pull data from FRF TDS and create the plots above: https://github.com/janahaddad/frf-obs 

you'll need to comment out everything in the "test" section in the Download script. Let me know if you run into issues!

**Comment by yunfangsun** [comment]
@janahaddad Thank you!
