### ISSUE TITLE
RT cases failed on Hercules for commit c6492b9 in the feature/coastal_app branch

### ISSUE THREAD

**Issue by yunfangsun** [oceanmodeling/ufs-weather-model#141]
Hi @uturuncoglu,

I have tried the `coastal_ike_shinnecock_ww3`, `coastal_ike_shinnecock_atm2ww3` and `coastal_ike_shinnecock_atm2sch2ww3` tests on Hercules, all the cases failed in the run_compile.

The error is caused by the path of NetCDF library:

```
CMake Error at CMakeLists.txt:163 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" (requested
  version 4.7.4) with any of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.
```

My log files are at /work2/noaa/nosofs/yunfangs/stmp/yunfangs/FV3_RT/rt_499916 and source code is at /work2/noaa/nosofs/yunfangs/ufs-11182024/ufs-weather-model on Hercules.

Thank you!

**Comment by uturuncoglu** [comment]
@yunfangsun I had a fresh clone and try to build one of the case `coastal_ike_shinnecock_atm2ww3 ` that you are trying to run and it builds without any issue. So, maybe it is just an environment issue in your end.

**Comment by uturuncoglu** [comment]
@yunfangsun If you are not using the head of our branch, you might want to update it.

**Comment by yunfangsun** [comment]
Thank you! The problem is solved.

**Comment by janahaddad** [comment]
@yunfangsun, did you just do a fresh clone and this worked, or another solution?

**Comment by yunfangsun** [comment]
@janahaddad 
I use module purge and `git submodule update --init --recursive`
