### ISSUE TITLE
ufs-coatal SCHISM+WW3 (DATM / PaHM)

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [oceanmodeling/ufs-weather-model#17]

**Comment by janahaddad** [comment]
Application of coupling PaHM + SCHISM + WW3, and building autoregression tests.

**Comment by saeed-moghimi-noaa** [comment]
@janahaddad @yunfangsun 

Here is my suggestion for steps for simulations to be completed, check marked and start the next step:
If needed break this down to multiple issues however linked to items here so we can use this to see where we are at any given time.

* Phase 1
- [ ]  stand alone SCHISM for Ian
- [ ] stand alone WW3 for Ian
- [ ] ufs-coastal SCHISM alone for Ian
- [ ] ufs-coastal WW3 alone for Ian
- [ ] ufs-coastal SCHISM-WW3 for Ian

* Phase 2
- [ ] Ask Ali to provide the wave boundary condition for Ian
- [ ] stand alone WW3 for Ian + open boundary
- [ ] ufs-coastal WW3 alone for Ian + open boundary
- [ ] ufs-coastal SCHISM-WW3 for Ian + open boundary

* Phase 3
- [ ]  Run Global and generate open boundary
- [ ] stand alone WW3 for Ian + open boundary
- [ ] ufs-coastal WW3 alone for Ian + open boundary
- [ ] ufs-coastal SCHISM-WW3 for Ian + open boundary

**Comment by janahaddad** [comment]
thanks @saeed-moghimi-noaa for putting this together.  Yunfang let's walk through each this afternoon

**Comment by janahaddad** [comment]
moving this issue from here to UFS-Coastal repo, and closing here...
