### ISSUE TITLE
Review draft items previously added to project

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#23]
Multiple items in the project are in draft mode. Review these with @pvelissariou1 and @saeed-moghimi-noaa.

**Comment by janahaddad** [comment]
I am curious if consolidating the project tracking on the [storm surge coordination project](https://github.com/orgs/noaa-ocs-modeling/projects/8) may work better.

**Comment by pvelissariou1** [comment]
@janahaddad Consolidation means?

**Comment by janahaddad** [comment]
It means we could exclusively use the storm surge coordination project
dashboard to track even these UFS-Coastal specific items. I.e., I would
move the project items listed in ufs-coastal to the other project
dashboard. I've noticed that there is a good number of items in the storm
surge coord project which are linked to repo. Do you think it would be
easier to just use one project page to track overall progress/tasks?

**Comment by saeed-moghimi-noaa** [comment]
Great idea. Please work with Takis to come up with a plan. I am all in for
removing redundancy as much as possible. -Saeed
______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.
