### ISSUE TITLE
Simulations for AMS

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#30]
1) The ECGC_2021_v2 mesh - fort.13+fort.14 (one also Aman shared) does not work, getting very large water levels after
    a few days into the simulation. I also added the slope limiter option but it didn't help.
2) The ECGC_2021_v2 that Yuji shared doesn't work either (this one used to work for me in the CoastalApp-testsuite).
    Thank you Yuji for sharing, your configs matched mine.
3) The 250m HSOFS mesh does not work either (very high water levels). This one used to work for me
     in the CoastalApp-testsuite runs (using NUOPC connectors and using previous commits)
4) The Atlantic_120m_relv3 mesh is the only mesh (fort.14+fort.13) that works for me.

**Comment by janahaddad** [comment]
@pvelissariou1 here's an issue to use for your current simulations

**Comment by pvelissariou1** [comment]
All AMS simulations were completed. Issues were identified for ADCIRC and CMEPS (1/2- way coupling) that will be discussed in relevant issues. I am closing this issue.
