### ISSUE TITLE
Update reg testing system to include Frontera

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#34]
## Description
Frontera support for ufs-coastal model is needed as second step in prepping for UFS Coastal/NUOPC walkthrough on March 1. 

## Solution
Add Frontera support 

## Related to
Follows #33

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 @saeed-moghimi-noaa This is almost done. I still need to fix couple of minor issues.

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 @saeed-moghimi-noaa @yunfangsun Please also note that we are using `flex` queue for compiling and running the RTs. The `normal` queue does not run jobs that uses less than 3 nodes. Anyway, if you have any idea about the queue that we need to use, just let me know and we could test it but I think `flex` is fine at this point.

**Comment by janahaddad** [comment]
closing & tracking in #43 instead
