### ISSUE TITLE
Create input files for tutorial reg test

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#35]
## Description
Set up of input files for reg testing, needed as third step in prepping for UFS Coastal/NUOPC walkthrough on March 1.

## Solution
Choose reg test -- SCHISM was requested -- from [one of the working reg tests ](https://github.com/oceanmodeling/ufs-coastal/wiki/Current-Status-of-UFS%E2%80%90Coastal-Implementation), & set up input files for the tutorial test with a short simulation time. 

## Related to
Follows #33 and #34

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 @saeed-moghimi-noaa I have already copy the input files. I have just need to fix the permission to allow others to access the input and spack-stack installation directories.

**Comment by janahaddad** [comment]
closing & tracking in https://github.com/oceanmodeling/ufs-coastal/issues/43 instead
