### ISSUE TITLE
Permissions on model component repos

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#38]
@uturuncoglu and/or @pvelissariou1 can you raise my permissions on the model component repos

[ADCIRC](https://github.com/oceanmodeling/adcirc), [FVCOM](https://github.com/oceanmodeling/fvcom), [SCHISM](https://github.com/oceanmodeling/schism), [SCHISM-ESMF](https://github.com/oceanmodeling/schism-esmf), [ROMS](https://github.com/oceanmodeling/roms), and [WW3](https://github.com/oceanmodeling/ww3) 

... so that I can manage these issues on the Surge Team Dashboard? 

Note that I already have the needed permissions on PaHM.

**Comment by uturuncoglu** [comment]
@janahaddad I did it. Please check and let me know if you have issue.

**Comment by janahaddad** [comment]
Looks good on my end, thanks!!
