### ISSUE TITLE
Finalize March 1 UFS-CAT Training Session 1 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#45]
@pvelissariou1 set up draft slides here: https://drive.google.com/drive/folders/12q5CBT3pniEAk6TTYGtWMlcEuCia3mCF 

We need to review & modify, and submit to @saeed-moghimi-noaa in time to make modifications for March 1 training: by Wed Morning 2/28

Related issue: #14 -- a few documentation updates to provide March 1 trainees. 
Related discussion: https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/discussions/289

**Comment by pvelissariou1** [comment]
The third version (close to the final version) of the slide deck includes all additions/suggestions of @uturuncoglu , @janahaddad and @atsay@ucar.edu (thank you) and a few new slides. There are a couple of slides that I will fill later today.
@saeed-moghimi-noaa , @uturuncoglu and all please take a look at the slide deck: https://docs.google.com/presentation/d/1D092z0E7Ol-0VORf-i4ydIMBOy8P7T3c-pJbjEgp43g/edit?usp=drive_link for last minute comments/suggestions.

**Comment by janahaddad** [comment]
Great work all! Thanks for all the work you put into making this a success @uturuncoglu @pvelissariou1 @yunfangsun @anntsay
