### ISSUE TITLE
Possible options to test for Frontera 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#48]
from Ufuk: (#33 ) BTW, we might need to modify Frontera part of tests/default_vars.sh little bit more (basically sets some number some cores, threading etc.) to run non coastal tests but I'll look at it later since our intention is limited with the ufs costal and also I don't have details all the variables used in there.

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 JFYI, I am plaining to update used compilers in the spack-stack installation on Frontera soon.

**Comment by janahaddad** [comment]
UFS-WM is working on Frontera support natively https://github.com/ufs-community/ufs-weather-model/pull/2265
