### ISSUE TITLE
Plan for upstream syncing with UFS-WM

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#49]
Develop a plan/list to git pull with ignore statements in place to exclude files we don't want to sync

**Comment by janahaddad** [comment]
https://github.com/ufs-community/ufs-weather-model/blob/develop/.gitignore 

as we agreed today, let's keep this issue focused to ignoring readme and license files. Goal is to have a good way of doing this when the readme and license language is agreed on by everyone

**Comment by janahaddad** [comment]
@uturuncoglu could we also ignore `doc/UsersGuide` since it's for UFS-WM ?

**Comment by uturuncoglu** [comment]
@janahaddad Let me do some experiment. I am working on issue related to SCHSIM at this point but I'll look at the one soon.

**Comment by janahaddad** [comment]
This is somewhat related to NOS Leadership guidance, so on-pause for now

**Comment by janahaddad** [comment]
Follow up from 5/20 tag-up: this issue will go away with planning move to ufs-coastal-app #71 

@uturuncoglu do you still think it's worth syncing again this week? Perhaps it's not worth the potential issues that will need to be resolved, and best to stick to a working version for the next month? What do you think?

**Comment by uturuncoglu** [comment]
@janahaddad Let's schedule next sync after I return. BTW, we could solve any issue that might arise in the sync process.

**Comment by janahaddad** [comment]
Ok thanks Ufuk. Understood regarding resolving sync issues -- I just didn't want that to be added to your pre-trip work load unnecessarily.
