### ISSUE TITLE
Update rt_coastal.conf file

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/ufs-weather-model#55]
## Description
As a part of following convention in the UFS Weather Model side, we might want to update `rt_coastal.conf` and get rid of number used in the name of the executable. For example, the following definition

```
COMPILE | 11 | intel | -DAPP=CSTLS -DUSE_ATMOS=ON -DNO_PARMETIS=OFF -DOLDIO=ON | | fv3 |
RUN | coastal_florence_hsofs.atm2sch | | baseline |
RUN | coastal_ike_shinnecock_atm2sch | | baseline |
```

would be

```
COMPILE | coastal_atm2sch | intel | -DAPP=CSTLS -DUSE_ATMOS=ON -DNO_PARMETIS=OFF -DOLDIO=ON | | fv3 |
RUN | coastal_florence_hsofs.atm2sch | | baseline |
RUN | coastal_ike_shinnecock_atm2sch | | baseline |
```

Also, it is hard to keep track those numbers.

## Solution
Update `rt_coastal.conf`

## Alternatives
N/A

## Related to
N/A

**Comment by uturuncoglu** [comment]
@pvelissariou1 Maybe as a part of your work and PR in ufs-coastal level, we could also update those names. It would be easier to understand which executable for which configuration rather than tracking those numbers in the executables.

**Comment by pvelissariou1** [comment]
@uturuncoglu Ok, I will eliminate the numbering sequence. Also we might want ro change fv3 to say UFS.x or something like that.

**Comment by pvelissariou1** [comment]
@uturuncoglu Let's talk about these today after the UFS-CAT meeting

**Comment by uturuncoglu** [comment]
@pvelissariou1 Sure. But changing fv3 could create downstream issues since it is prefix and also I don' want to modify rt.sh extensively. If we would like to make that changes, that needs to be in the UFS Weather Model level.
