### ISSUE TITLE
Set up & test (Orion/Hercules) updated configs for SCHISM, ADCIRC, WW3 RTs

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#58]
- For Shinnecock cases, H. Sandy forcing, on Orion/Hercules

Note that running without CMEPS is not a priority for the UFS-CAT tutorial 

- Set up configuration with connector
- Activate removal of ghost elements on the model component side
- pass to CDEPS
- run RT

Related issue: https://github.com/ESCOMP/CDEPS/issues/249

@pvelissariou1 please add detail and comment as needed

**Comment by pvelissariou1** [comment]
The following regression tests (RT) for SCHISM are being updated:

1. ATM2SCH - schism configuration/input files have been updated (shinnecock)
2.  ATM2SCH - schism configuration/input files updated partially (atlantic)
3. ATM2SCH2WW3 - config/input files for WW3 have been updated (shinnecock) - to be finalized
4. ATM2SCH2WW3 - pending (atlantic)
5. PAM2SCH - confing/input files have been updated (shinnecock)
6. PAM2SCH2WW3 - same status as case ATM2SCH2WW3
7. PAM2SCH - confing/input files have been updated partially (atlantic)
8. PAM2SCH2WW3 -pending (atlantic)

Baselines are being created for all cases. ATM2SCH/PAM2SCH (shinnecock) cases passed the baseline comparisons (Intel compilers on orion/hercules).
- Need to check on frontera - pending

Need to push UFS-Coastal & RT folder upstream - pending

**Comment by pvelissariou1** [comment]
The RTs for UFS-Coastal that have been configured and being tested are:
**A) SCHISM**
1. coastal_idealized_shinnecock_atm2sch (previously coastal_ike*)
2. coastal_idealized_shinnecock_sch (previously coastal_ike*)
3. coastal_sandy_shinnecock_atm2sch
4. coastal_sandy_shinnecock_sch
5. coastal_idealized_shinnecock_atm2sch2ww3 (previously coastal_ike*)
6. coastal_idealized_shinnecock_atm2sch2ww3
7. coastal_sandy_shinnecock_sch_pam

**B) ADCIRC**
1. coastal_idealized_shinnecock_atm2adc
2. coastal_sandy_shinnecock_atm2adc
3. coastal_idealized_shinnecock_atm2adc2ww3
4. coastal_sandy_shinnecock_atm2adc2ww3

**C) WW3**
1. coastal_idealized_shinnecock_ww3
2. coastal_idealized_shinnecock_atm2ww3

**Comment by janahaddad** [comment]
Update from @pvelissariou1: 

* all configs listed above have been updated
* SCHISM version in UFS-Coastal has been updated
* Takis is testing  them on Orion now

**Comment by janahaddad** [comment]
Update 4/4: 
ufs-coastal compiles fine on all platforms
on Orion, SCHISM RTs are passing and replicating previous results

**Comment by pvelissariou1** [comment]
On /Hercules/Orion:
- coastal_**idealized**_shinnecock_atm2sch (pass)
- coastal_**idealized**_shinnecock_sch (pass)
- coastal_**idealized**_shinnecock_atm2sch2ww3 (pass)
- coastal_**sandy**_shinnecock_atm2sch (pass)
    - Need to create new tidal boundary conditions
- coastal_**sandy**_shinnecock_sch (pass)
    - Need to create new tidal boundary conditions
- coastal_**sandy**_shinnecock_atm2sch2ww3 (pass)
    - Need to create new BCs for SCHISM (tidal) & WW3
- coastal_**sandy**_shinnecock_sch_pam  (pass)

NOTE1: waiting to get AVISO FES2014 data access (need to check with @bahram if has already downloaded the data) to set proper tidal boundary conditions for SCHISM
NOTE2: Need to interact with @yunfangsun for the WW3 BCs

**Comment by janahaddad** [comment]
@pvelissariou1 are any of these without BCs ready for a pull request?

**Comment by janahaddad** [comment]
https://github.com/oceanmodeling/ufs-coastal/pull/68

**Comment by saeed-moghimi-noaa** [comment]
@yunfangsun 

RTs for ww3+schism with and with out wave boundary conditions.

**Comment by janahaddad** [comment]
@pvelissariou1 can you please share locations for these two RTs: 

coastal_florence_hsofs_atm2adc2ww3 
coastal_florence_hsofs_atm2sch2ww3_nobc

**Comment by pvelissariou1** [comment]
Answered this in https://github.com/oceanmodeling/ufs-coastal/issues/59

**Comment by janahaddad** [comment]
Closing per @saeed-moghimi-noaa 's suggestion, see #72
