### ISSUE TITLE
Test SCHISM, ADCIRC, WW3 updated RTs on Frontera, Hera 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#59]
@pvelissariou1  will test oceanmodeling/ufs-coastal#58 on Frontera after the  current Orion tests are done

_Originally posted by @janahaddad in https://github.com/oceanmodeling/ufs-coastal/issues/43#issuecomment-2030327446_

**Comment by janahaddad** [comment]
@pvelissariou1 can @yunfangsun help with this over the next couple weeks?

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 @yunfangsun The Frontera support officially merged to spack-stack development branch. https://github.com/JCSDA/spack-stack/pull/1075. This uses newer version of the Intel compiler. I did not test this with ufs-coastal yet but I'll do it when I have time.

**Comment by pvelissariou1** [comment]
@uturuncoglu Thanks ufuk. I need to update the inernal document.

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 

Takis,

Please let @yunfangsun access the folders in which you work on the two test cases (with and with out wave boundary conditions). 

Thanks,
-Saeed

**Comment by pvelissariou1** [comment]
The RT folder is open (read) located in Orion/Hercules at: /work/noaa/nosofs/pvelissa/RT-03132024
Cases need some work, I usually push updated data from my desktop to that folder.
I opened the folder with read/write permissions for groups only. @yunfang please let me know for scheduled modifications from you (if any) to avoid any conflicts.

**Comment by saeed-moghimi-noaa** [comment]
@pvelissariou1 

I assume the one with out wave boundary condition is already included in the standard RTs within ufs-coastal, right?

Thanks

**Comment by saeed-moghimi-noaa** [comment]
@janahaddad @pvelissariou1 @yunfangsun  

Suggest to separate this issue into two issues:
1. New RT for schism + ww3 with wave boundary condition (assign to Yunfang - perhaps a new issue)
2. New RT for adcirc + ww3 with wave boundary condition (pause for now - perhaps this issue)

**Comment by pvelissariou1** [comment]
@saeed-moghimi-noaa Yes, I have created all necessary configs for the test cases. The branch to be cloned is: `git clone https://github.com/oceanmodeling/ufs-coastal.git -b cmmb`
I am using this branch for the RT development and other fixes. There is already a PR to merge with the main. Need to finalize a few things and then I'll talk with Ufuk to merge anything tthat is not included after his sync with the ufs-weather-model.

**Comment by saeed-moghimi-noaa** [comment]
> @saeed-moghimi-noaa Yes, I have created all necessary configs for the test cases. The branch to be cloned is: `git clone https://github.com/oceanmodeling/ufs-coastal.git -b cmmb` I am using this branch for the RT development and other fixes. There is already a PR to merge with the main. Need to finalize a few things and then I'll talk with Ufuk to merge anything tthat is not included after his sync with the ufs-weather-model.

Thanks Takis.
