### ISSUE TITLE
Documentation: add instructions on how to use spack-stack across different platforms

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#69]

**Comment by pvelissariou1** [comment]
@janahaddad , @AtiehAlipour-NOAA , @saeed-moghimi-noaa I will put all the information here for the different platforms (and the different versions of spack-stack. Keep in mind that the version of spack-stack, paths and libraries change as they update spack-stack. Good thing is that they keep 2-3 previous versions after each update. @AtiehAlipour-NOAA Atieh let me know if it is ok to put all the information here and if it is easy for you to update your guides. We will have a brief meeting tomorrow.

**Comment by AtiehAlipour-NOAA** [comment]
@pvelissariou1, I would be happy to help. The guides are just a list of markdown files (.md). Each one of us, when we learn/develop something that we think can be useful for others, can create one in the guides folder. [Here ](https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/blob/main/guides/dask_on_rdhpcs.md) is an example that Yunfang added. We can meet tomorrow and create one together for using Spack-stack across different platforms.

**Comment by janahaddad** [comment]
@pvelissariou1 is the documentation here still relevant: https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#noaa-rdhpcs-hera ? this is just the Hera one but they have instructions for each Tier 1 platform there too

**Comment by pvelissariou1** [comment]
@janahaddad It is for building spack-stack (somehow relevant, I'll insert a link into the documentation so we can have all the info in one place). The documention will have user directed instructions on how to load spack-stack libraries outside ufs-coastal for "everyday" usage. Thanks for checking.

**Comment by janahaddad** [comment]
@pvelissariou1 has compiled these instructions here: https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/blob/main/guides/spack-stack_rdhpcs.md thank you Takis!
