### ISSUE TITLE
model repo name change & transition to coastal-app repo as landing page

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#71]
Follows #47, #70 , and recent conversations. This will involve adding the finalized readme draft to the `ufs-coastal-app` repo, moving the Wiki there, and moving the Discussions there, and indicating these changes on `ufs-coastal` repo

**Comment by janahaddad** [comment]
Steps:
- [x] alert users (UFS-CAT testers)
- [x] rename ufs-coastal to ufs-weather-model (target Friday 5/21)
- [x] at app level: may need to update submodule 
- [x] add readme.md to [ufs-coastal-app](https://github.com/oceanmodeling/ufs-coastal-app) 
- [x] add license.md to [ufs-coastal-app](https://github.com/oceanmodeling/ufs-coastal-app) 
- [ ] update Sphynx documentation source files to read "ufs coastal app" 
- [x] check/update other things e.g. build script on app-level (or move to branch) 
- [ ] Move Wiki, Discussions, and Project 

Target Wed 5/29 for transition 

5/29 update: We've added readme file to app-level. Ufuk has tested the initial build script there and updated the model submodule. Will wait for Ufuk's return to complete remaining steps above.

**Comment by uturuncoglu** [comment]
@janahaddad @saeed-moghimi-noaa @pvelissariou1 I just wonder about the current situation of this transition. Are we planing to rename the ufs-coastal as ufs-weather-model repo today? If so, I could do it and if you could provide README file for app level, I could also add it to the application level. I think I could also make quick change in the documentation and replace ufs-coastal references as ufs-weather-model. Anyway, let me know what you think. BTW, I think we did not inform model developers about this transition. I think it would be nice to send mail to Hernan, Joseph etc. about it.

**Comment by janahaddad** [comment]
Hey @uturuncoglu, yes I think let's do this today. Once I prep the readme.md can I push or PR to the app level?

**Comment by janahaddad** [comment]
@josephzhang8, @hga007, @AliS-Noaa, @aliabdolali, @sbanihash, @yunfangsun, @Armaghan-NOAA, @jkbk2004 -- please be aware that we are making the following repo name change imminently: 

As the UFS Coastal project begins app-level development, we're planning on shifting the primary landing page of the project to the [app-level repo](https://github.com/oceanmodeling/ufs-coastal-app). As part of that, we're changing the current forked model-level repo name from `ufs-coastal` back to `ufs-weather-model`.  The model-level code base will exist as a submodule within the app-level. 

Once the name change is made, the impact on users will be a change in the clone command line code. To download the model-level repo directly, users should use: 

`git clone --recursive https://github.com/oceanmodeling/ufs-weather-model.git`

**Comment by janahaddad** [comment]
@josephzhang8, @hga007, @AliS-Noaa, @aliabdolali, @sbanihash, @yunfangsun, @Armaghan-NOAA, @jkbk2004 @pvelissariou1 @gseroka @ayumifuji @odotyy 

please note that this name change has occurred! We'll continue the transition over the summer to ufs-coastal-app as the landing page following the steps listed above. Thanks all.

**Comment by uturuncoglu** [comment]
@janahaddad I also update application level build to accommodate the change in the repo name. It is in the main branc at this point and tested on Hercules. Here are the commands that I am using,

- checkout app
```
git clone --recursive https://github.com/oceanmodeling/ufs-coastal-app.git
cd ufs-coastal-app
```

- build model
```
./build.sh --app=CSTLS --compiler=intel --build-dir=$PWD/build --install-dir=$PWD/install --platform=hercules
```

So, this compiles DATM+SCHSIM configuration on MSU's Hercules with intel compiler. All the executables are in $PWD/install/bin directory (i.e. model executable is named as `ufs_model` and tools related with SCHSIM are also in the same directory). Of course, I still need to work on app level build to fix the remaining issues but this is good starting point. I am not sure I could able to update the documentation to remove the all the references to ufs-coastal but I'll let you know if I could.

**Comment by janahaddad** [comment]
Thank you @uturuncoglu
