### ISSUE TITLE
Testing UW tools

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#78]

**Comment by uturuncoglu** [comment]
JFYI, the conversation with UWTools is happening in here: https://github.com/ufs-community/uwtools/discussions/478

**Comment by janahaddad** [comment]
great, thanks Ufuk

**Comment by janahaddad** [comment]
more update and next steps documented at today's tag-up:  #5

**Comment by janahaddad** [comment]
Closing this since it's being updated/tracked on the ufs-coastal-app repo
