### ISSUE TITLE
UFS Mapping feedback for leadership

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/ufs-weather-model#87]
Adding UFS Coastal planned prototype applications and included components on [UFS / EPIC models and components](https://docs.google.com/spreadsheets/d/13KwjNuCQxS2dQHPuSD3sdHbEHDXA81yamGaI5Uyq1ds/edit#gid=0) spreadsheet per Hendrik Tolman request

Basis for prototype applications is Saeed's list for UIFCW:

SECOFSt: DATM+SCHISM+WW3 (funded)
ROMS regression test: DATM+ROMS+WW3 (funded)
STOFS-3D-Alaska: DATM+SCHISM+CICE+WW3 (partially funded)
STOFS workflow:To unify and upgrade current STOFS workflow (partially funded)
Hurricane-Surge: PAHM+SCHISM+WW3 (partially funded)
STOFS-2D-Global: DATM+ADCIRC+WW3 (not funded)

**Comment by janahaddad** [comment]
@saeed-moghimi-noaa will follow up with you in case we need to review together, but take a look at my first pass when you have a chance. 

Note that I didn't include STOFS workflow upgrade because I think it could be covered (for this mapping exercise) within the other two STOFS apps (STOFS-3D alaska & STOFS 2D global)

**Comment by saeed-moghimi-noaa** [comment]
I agree

**Comment by janahaddad** [comment]
reviewed & shared

**Comment by saeed-moghimi-noaa** [comment]
> reviewed & shared

Thanks @janahaddad
